### ISSUE TITLE
how to get the pkl data by my own data

### ISSUE THREAD

**Issue by SmalWhite** [Xiangyi1996/PPNet-PyTorch#1]
Firstly, I really appreciate your work, thank u very much!
But, I have some question about the data in this experiment:
1) what the pkl data mean?
2) how can i get the pkl data by my own data.
looking forward to your reply!
thanks again.

**Comment by youngfly11** [comment]
Hi, the Pickle data is the superpixel results of all images in the datasets. We use SLIC to generate this superpixel results, you can find that repo in the github.

**Comment by SmalWhite** [comment]
ok! thank for your patience.

**Comment by SmalWhite** [comment]
Hello again, I found the SLIC in https://github.com/jayrambhia/superpixels-SLIC , but it may not the SLIC used in the project. It can't be better anymore, if you can show the SLIC link you used in this project. Thank you very much!

**Comment by Xiangyi1996** [comment]
We use the `from fast_slic.avx2 import SlicAvx2`this util to generate the superpixels.
The reference link: [https://github.com/Algy/fast-slic](url)

**Comment by SmalWhite** [comment]
Thanks
