### ISSUE TITLE
关于background prototype的问题

### ISSUE THREAD

**Issue by ily666666** [Xiangyi1996/PPNet-PyTorch#12]
刚刚看完您的论文，有个问题想问一下，在论文中没有看到关于background prototype是如何生成的，但是在图1左下角出现了background prototype， 所以我想问一下background prototype是如何生成的，并且它的作用是什么？

**Comment by youngfly11** [comment]
Hi;
You can treat the background as a normal special class.  All prototypes of background are generated as the same as other classes.
