### ISSUE TITLE
关于background prototype的问题

### ISSUE THREAD

**Issue by ily666666** [Xiangyi1996/PPNet-PyTorch#13]
请问是类别k的每张支持集图片的生成一个background prototype吗？ 谢谢

**Comment by Xiangyi1996** [comment]
每一张support image的背景部分的feature聚类成N_p个background prototype。

**Comment by ily666666** [comment]
好的，我还想详细了解一下，你们的图神经网络是怎么实现的，请问该参考哪篇论文？

**Comment by youngfly11** [comment]
Thanks for your attention to our work.
I think you can dive into codes for details. Our graph net is the simplest graph attention network, which is widely used in other projects.
