### ISSUE TITLE
Hello again, I found the SLIC in https://github.com/jayrambhia/superpixels-SLIC , but it may not the SLIC used in the project. It can't be better anymore, if you can show the SLIC link you used in this project. Thank you very much!

### ISSUE THREAD

**Issue by SmalWhite** [Xiangyi1996/PPNet-PyTorch#2]
Hello again, I found the SLIC in https://github.com/jayrambhia/superpixels-SLIC , but it may not the SLIC used in the project. It can't be better anymore, if you can show the SLIC link you used in this project. Thank you very much!

_Originally posted by @SmalWhite in https://github.com/Xiangyi1996/PPNet-PyTorch/issues/1#issuecomment-683667282_

**Comment by Xiangyi1996** [comment]
We use the from fast_slic.avx2 import SlicAvx2this util to generate the superpixels.
The reference link: https://github.com/Algy/fast-slic
