### ISSUE TITLE
Can i run it in windows?

### ISSUE THREAD

**Issue by gaowq2017** [Xiangyi1996/PPNet-PyTorch#3]
Hi@Xiangyi1996, I can't run the code in windows because the pykeops module of kmeans is not exist in windows. Can i use common kmeans module replace it? Do you any good ideas? Thank you!

**Comment by youngfly11** [comment]
Hi, gaowq, 
we have no plan and no time to transplant our code to the Windows platform. So you can try whatever you want. Thanks.
