### ISSUE TITLE
As for the package pykeops

### ISSUE THREAD

**Issue by qqqlz** [Xiangyi1996/PPNet-PyTorch#4]
Your work is really attactive.

After looking through the code, I find you use the LazyTensor from the pykeops, I want to know why you don't use Tensor.
If there is any difference between the use of LazyTensor and Tensor.

Thank you

**Comment by youngfly11** [comment]
Hi, qqqlz;

Thanks for your interest.  You can refer to this link for detail: https://www.kernel-operations.io/keops/_auto_tutorials/kmeans/plot_kmeans_torch.html. We just follow the official implementation as shown in pykeops.
