### ISSUE TITLE
About compute of the prototype

### ISSUE THREAD

**Issue by gaowq2017** [Xiangyi1996/PPNet-PyTorch#5]
Hi Xiangyi,
     I can't find the compute of µij with eq.(2) in source code. The global prototype can replace it or others? Thanks
![image](https://user-images.githubusercontent.com/29697367/92218463-c2ab4f00-eecb-11ea-8382-cc7b5754f8c5.png)

**Comment by youngfly11** [comment]
Hi; gaowq;

We just simplify the model design conceptually.  There are two reasons for doing so:

1. the network can learn easier without many unnecessary parameters. 
2. We just want to conduct a clear message passing (without any background noise) within the foreground object.  we believe that the importance of each part is in the proportion of their size.  and actually this kind of simplification works well in reality. 
Thanks.
